# serverless.yml

service: serverless-flask-test

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.serverless.routes
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: python3.8

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'