org: darylron
app: image-upload-app

service: image-upload-api

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.Routes
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: python3.8

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - S3:*
      Resource: '*'

functions:
  app:
    handler: wsgi.handler
    environment:
      AWS_S3_IMAGE_BUCKET: 'secretairbucket'
      AWS_S3_REGION: 'ap-northeast-1'
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  resize:
    handler: app.img_processor.s3event.call
    environment:
      BUCKET: secretair91-resized-images1
      REGION: ap-northeast-1
    events:
      - http:
          path: /{width}/{image}
          method: get
